### ISSUE TITLE
scrcpy start后报错

### ISSUE THREAD

**Issue by iamqiqi1017** [UrielCh/adbkit#20]
我遇到了一个问题 在启动scrcpy start后报错
![image](https://github.com/UrielCh/adbkit/assets/78333511/5fd2d7b8-0df4-4ae7-a293-a469c8ec7d25)
安卓版本是12 使用的redroid ，使用官方的scrcpy工具是正常的

**Comment by UrielCh** [comment]
is the error is throw by the line 167
```ts
          try {
            this.emit('error', Error(msg)); // Line 167
          } catch (e) {
            // emit Error but to not want to Quit Yet
          }
```
the error append in the java stack... so the issue can be fix by patching scrcpy, by the way you can try to change your USB wire that use to fix the issue.

improve this error handeling is a bit complicated.

**Comment by iamqiqi1017** [comment]
我fork了你的项目然后修改了一部分代码 现在已经解决了 貌似是scrcpy版本和传参的问题
