### ISSUE TITLE
Add TCP connector to avoid ADB binary

### ISSUE THREAD

**Issue by sharpordie** [UrielCh/adbkit#6]
Currently this library requires an official ADB binary to work.
It would be great to implement TCP connector like in the [dadb](https://github.com/mobile-dev-inc/dadb) and [adb_shell](https://github.com/JeffLIrion/adb_shell) libraries and avoid this ADB binary requirement.

**Comment by UrielCh** [comment]
Good suggestion.

thx.

**Comment by UrielCh** [comment]
is the a nodeJS version ?
