### ISSUE TITLE
Scrcpy.start() does not resolve

### ISSUE THREAD

**Issue by thelicato** [UrielCh/adbkit#9]
Hi, I was trying to use the Scrcpy class you implemented but the ``start`` method does not resolve. The execution gets stuck. Here is a snippet of my current code:
```
const snippet = async () => {
	const devices = await client.listDevices();
	if (devices.length == 0) {
		return
	}

	const device = devices[0].getClient()
	const scrcpy = device.scrcpy({})
	console.log("Starting")
	await scrcpy.start()
	console.log("Started")
}
```

It never reaches the last ``console.log``

**Comment by UrielCh** [comment]
Please try to use a debugger to find where the code gets stuck.

I can not reproduce this issue.
At least provide your android version

**Comment by thelicato** [comment]
The code gets stuck at [this line](https://github.com/UrielCh/adbkit/blob/ca642b6d37ef83f6d9c6cf361a256fc47ec59166/src/adb/thirdparty/scrcpy/Scrcpy.ts#L335). Here is a screenshot of the ``this.scrcpyServer`` object: 

![image](https://user-images.githubusercontent.com/20096272/193524578-5e1bf16a-1b29-487d-a898-3669f0378ffb.png)

Here is some info about my tests:
- **@u4/adbkit version**: 4.1.10
- **Android versions**: 10, 11, 12
- **Platform Tools**: Android Debug Bridge version 1.0.41 / Version 28.0.2-debian

Can you provide a snippet of code that works for you?

**Comment by thelicato** [comment]
I got it working using the ancient solution: **revert back to a previous version**. I tried many different versions and the results are the following:
- **_version_ < 4.1.3**: It works
- **4.1.3 <= _version_ < 4.1.8**: Throws the error ``AdbFailError: Failure: 'closed' lastMessage:host:transport:3da00e49``
- **_version_ >= 4.1.8**: It gets stuck

**Comment by UrielCh** [comment]
check the file named: tasks/realTest.ts it contains working test code for most functions.

**Comment by thelicato** [comment]
I confirm that the result is the same also with the code you provided in ``tasks/realTest.ts``. If I don't revert back to ``4.1.2`` or previous it does not work.

**Comment by daniele-capone** [comment]
I have exactly the same issue as thelicato: it works only with version ``4.1.2`` and previous. I also have ``adb`` version ``1.0.41``, maybe that's the problem: what is your adb version?

**Comment by UrielCh** [comment]
I'm not working on [remote-droid](https://hub.docker.com/repository/docker/urielch/remote-droid), a REST connector for adbkit,
and his front-end, currently I'm only using minicap jpeg to display the device; after that, I will switch back to video mode and then fix that issue. Keep the old version for now. This project is currently pretty active.

If you have already integrated adbkit video stream in a browser, and you can help, I can debug that next week.

**Comment by UrielCh** [comment]
just tested, and just fixed it.
v4.1.11

**Comment by thelicato** [comment]
Great, thanks!
